Add JetBrain's DataGrip/IntelliJ
tarantool/awesome-tarantool pull request #7
Opened 2021-08-27 13:04 UTC by kokizzu

I think this one the best IDE for Tarantool for now.
![image](https://user-images.githubusercontent.com/1061610/131131652-f239cb0c-69d6-4d9d-ba87-1021cc64f010.png)

2021-08-29 20:29 UTC, tsafin requested changes
Tarantool plugin for DataGrip/IDEA is not yet fully released, so this addition is a little bit premature. But thanks for reminding - once all set we should add DataGrip to the list.

2021-09-17 19:11 UTC, Periecle commented
@kokizzu, I think we can update links in PR and proceed with merge. 
Link: https://plugins.jetbrains.com/plugin/17422-tarantool-database

2021-09-18 15:47 UTC, tsafin approved these changes

2021-09-18 17:52 UTC, Totktonada commented
Squashed commits, camelcased product names (as it is written on the official website).

2021-09-18 18:06 UTC, merged